### ISSUE TITLE
They who?

### ISSUE THREAD

**Issue by pinver** [jasonwhite/button-rs#1]
Sorry to bother you here, but I don't know where to ask (at least, an incentive to a better README)!

I'm using button in the D implementation, do you think you will keep both implementation up-to-date?
For curiosity, can you tell something about why you were asked to rewrite button in rust? Maybe in the D forum?

Thanks, and sorry again!

**Comment by jasonwhite** [comment]
Shoot. I just saw this issue. Not sure how I missed it.

I had no idea anyone was using the D implementation of Button. I'm pleasantly surprised. :)

The repo description was a joke about the Rewrite It In Rust (RIIR) mantra in the Rust community. No one asked me to rewrite it in Rust. There were deep changes I wanted to make to Button based on things I've learned and it seemed easier to start from scratch. I've also abandoned the D language for Rust. I feel it is a better designed language with a superior ecosystem. Whenever I rewrite a D tool in Rust, it just feels like rock-solid software.

Right now this project is still very much a work in progress, so I'm not ready to put up a README yet.
